apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sero.serviceAccountName" . }}
rules:
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments", "replicasets"]
  verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sero.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "sero.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "sero.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
