apiVersion: v1
kind: Service
metadata:
  name: {{ include "sero.fullname" . }}
  labels:
    {{- include "sero.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 2112
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "sero.selectorLabels" . | nindent 4 }}
